backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/articles'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'relation', collection: 'authors', value_field: "{{name}}", search_fields: ["name"], display_fields: ['{{name}}']}
      - { label: 'Image', name: 'img', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'authors'
    label: 'Authors'
    folder: 'content/authors'
    format: 'frontmatter'
    create: true
    slug: '{{name}}'
    editor:
      preview: false
    fields:
      - {label: 'Name', name: 'name', widget: 'string'}
      - {label: 'Bio', name: 'bio', widget: 'text'}
  - name: 'technos'
    label: 'Technos'
    folder: 'content/technos'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - {label: 'Name', name: 'title', widget: 'string'}
      - {label: 'Logo', name: 'img', widget: 'image'}
      - {label: 'Lien', name: 'link', widget: 'image'}
      - {label: 'Lien', name: 'home', widget: 'boolean'}
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'About Page'
        name: 'about'
        file: 'content/about.yml'
        fields:
          - {label: 'First title', name: 'first-title', widget: 'string'}
          - {label: 'Fist body', name: 'first-body', widget: 'markdown'}
          - {label: 'Second title', name: 'second-title', widget: 'string'}
      - label: 'Home page'
        name: 'home'
        file: 'content/home.yml'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Description', name: 'description', widget: 'text'}
          - {label: 'Button text', name: 'button', widget: 'string'}
          - {label: 'Section 1 title', name: 'section-1-title', widget: 'string'}
          - {label: 'Section 1 content', name: 'section-1-content', widget: 'markdown'}
          - {label: 'Section 2 title', name: 'section-2-title', widget: 'string'}
